org.gradle.jvmargs = -Xmx8192m -XX:MaxMetaspaceSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true

loom.platform = neoforge

mod_version = 1.4.5
maven_group = me.kall.lookinmyeyes
archives_name = lookinmyeyes

# Minecraft properties
minecraft_version = 1.21.1
neoforge_version = 21.1.192
parchment_version = 2024.11.17

cf_project_id=1309252