org.gradle.jvmargs = -Xmx8192m -XX:MaxMetaspaceSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true

loom.platform = forge

mod_version = 1.4.4
maven_group = me.kall.lookinmyeyes
archives_name = lookinmyeyes

minecraft_version = 1.19.2
forge_version = 43.5.0
parchment_version=2022.11.27

mixinextras_version = 0.4.1

cf_project_id=1309252